# netlify.toml - configurazione per Next.js

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ambiente di sviluppo locale (opzionale)
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
